const $ = id => document.getElementById(id);
const comps = $('comps');
const tpl = $('compTemplate');
let saved = JSON.parse(localStorage.getItem('resale_items') || '[]');
function money(n){return '$' + (isFinite(n)?Math.round(n):0).toLocaleString();}
function addComp(data={}){const node=tpl.content.cloneNode(true);const el=node.querySelector('.comp');el.querySelector('.sold').value=data.sold||'';el.querySelector('.ship').value=data.ship||'';el.querySelector('.match').value=data.match||'1';el.querySelector('.source').value=data.source||'';el.querySelector('.remove').onclick=()=>{el.remove();calc();};el.querySelectorAll('input,select').forEach(x=>x.addEventListener('input',calc));comps.appendChild(node);calc();}
function getCompValues(){return [...document.querySelectorAll('.comp')].map(c=>({sold:+c.querySelector('.sold').value||0,ship:+c.querySelector('.ship').value||0,match:+c.querySelector('.match').value||1,source:c.querySelector('.source').value.trim()})).filter(c=>c.sold>0);}
function calc(){const vals=getCompValues();const condition=+$('condition').value;let weighted=0,weight=0;vals.forEach(c=>{weighted+=(c.sold+c.ship)*c.match;weight+=c.match;});const avg=weight?weighted/weight*condition:0;const list=avg*1.08;const quick=avg*.75;const hold=avg*1.25;const maxBuy=avg*.35;const cost=+$('buyCost').value||0;const fees=list*.15;const profit=list-fees-cost;$('avgSold').textContent=money(avg);$('quickPrice').textContent=money(quick);$('listPrice').textContent=money(list);$('holdPrice').textContent=money(hold);$('maxBuy').textContent=money(maxBuy);$('profit').textContent=money(profit);let call='Add comps to get a recommendation.';if(vals.length){ if(cost && cost<=maxBuy*.7) call='BUY: plenty of margin.'; else if(cost && cost<=maxBuy) call='BUY if condition and demand are solid.'; else if(cost) call='PASS unless it is rare or easy to sell locally.'; else call='Target buy price: '+money(maxBuy)+' or less.';} $('buyCall').textContent=call; return {avg,list,quick,hold,maxBuy,profit,vals};}
function renderSaved(){savedItems.innerHTML=saved.length?'':'<p>No saved items yet.</p>';saved.slice().reverse().forEach(item=>{const d=document.createElement('div');d.className='savedItem';d.innerHTML=`<strong>${item.name||'Untitled item'} — ${money(item.list)}</strong><small>${item.category} · ${item.conditionText} · Max buy ${money(item.maxBuy)} · ${new Date(item.date).toLocaleDateString()}</small><p>${item.notes||''}</p>`;savedItems.appendChild(d);});}
function saveItem(){const r=calc();const item={date:new Date().toISOString(),name:$('itemName').value.trim(),category:$('category').value,conditionText:$('condition').selectedOptions[0].text,condition:$('condition').value,buyCost:$('buyCost').value,notes:$('notes').value.trim(),...r};saved.push(item);localStorage.setItem('resale_items',JSON.stringify(saved));renderSaved();}
function exportCsv(){const rows=[['Date','Item','Category','Condition','Buy Cost','Avg Sold','Quick Price','List Price','Hold Price','Max Buy','Profit','Notes']];saved.forEach(i=>rows.push([i.date,i.name,i.category,i.conditionText,i.buyCost,Math.round(i.avg),Math.round(i.quick),Math.round(i.list),Math.round(i.hold),Math.round(i.maxBuy),Math.round(i.profit),i.notes]));const csv=rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='resale_items.csv';a.click();}
function clearForm(){['itemName','buyCost','notes'].forEach(id=>$(id).value='');comps.innerHTML='';addComp();}
['condition','buyCost'].forEach(id=>$(id).addEventListener('input',calc));$('addComp').onclick=()=>addComp();$('saveItem').onclick=saveItem;$('exportCsv').onclick=exportCsv;$('clearForm').onclick=clearForm;addComp();renderSaved();
if('serviceWorker' in navigator){navigator.serviceWorker.register('sw.js').catch(()=>{});}
